language: java
jdk:
- openjdk10
before_install:
- chmod +x build.sh
deploy:
  provider: script
  script: bash build.sh
  on:
    branch: master
notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
      - bren@juanantonio.info
script:
  - ./build.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)


